### ISSUE TITLE
Error in Rcpp::sourceCpp("./for_r.cpp") :

### ISSUE THREAD

**Issue by soundharramsay** [awjga/PORE-cupine#2]
Congrats on the excellent work. 

I am encountering the following error in the below step 

#To combine multiple events from same position and strands
./Read_events.R -f gene.event -o combined.RData
![Capture](https://user-images.githubusercontent.com/32353704/123193054-0a44ab00-d4df-11eb-81d2-a960b46e85b1.PNG)

Thanks

**Comment by soundharramsay** [comment]
A updated version of the "for_r.cpp" file was given by the author in the PORE-cupine. It run without any error.

**Comment by Kevinzjy** [comment]
Hi @soundharramsay , I've encountered the same error. Could you share the updated version of "for_r.cpp" here?

Update: I replaced the "PORE-cupine/for_single_gene/for_r.cpp" with "PORE-cupine/for_r.cpp", and it works like a charm

**Comment by soundharramsay** [comment]
Hey update script is in the first page of porecupine GitHub...as of the
same name for_r.cpp

**Comment by Kevinzjy** [comment]
Thanks for your help! @soundharramsay
